"""Runtime/provider-neutral discovery and resolution; no worker lifecycle."""

from .compatibility import legacy_local_compatibility, load_compatibility_bindings
from .discovery import discover_execution_facts, endpoint_locality, provider_locality
from .domain import (
    AgentRuntime,
    Compatibility,
    DiscoveryFacts,
    ExecutionCapabilities,
    ExecutionPolicy,
    ExecutionTarget,
    ExecutionTargetKey,
    LaunchBindingKey,
    LaunchCapability,
    LaunchStrategy,
    Locality,
    MachineCapabilities,
    Model,
    ModelProvider,
)
from .model_providers import (
    PROVIDER_PROBE_REGISTRY,
    DiscoveredModel,
    ModelProviderProbe,
    ProviderProbeRegistry,
    register_provider_probe,
    unregister_provider_probe,
)
from .serialize import (
    CANONICAL_EXECUTION_FIELDS,
    COORDINATOR_GATES,
    EXECUTION_TARGET_CONTRACT_VERSION,
    LAUNCH_PROOF_OPERATION,
    LEGACY_COMPATIBILITY_FIELDS,
    OWNERSHIP_METADATA,
    build_execution_policy,
    coordinator_gate_from_event,
    prove_launch_invocation,
    resolve_mode_c_execution,
    safe_endpoint_for_context,
    serialize_execution_policy,
    serialize_execution_target,
    serialize_launch_candidate,
)
from .targets import combine_capabilities, expand_compatibility, resolve_targets

__all__ = [
    "AgentRuntime",
    "CANONICAL_EXECUTION_FIELDS",
    "COORDINATOR_GATES",
    "Compatibility",
    "DiscoveredModel",
    "DiscoveryFacts",
    "EXECUTION_TARGET_CONTRACT_VERSION",
    "ExecutionCapabilities",
    "ExecutionPolicy",
    "ExecutionTarget",
    "ExecutionTargetKey",
    "LAUNCH_PROOF_OPERATION",
    "LEGACY_COMPATIBILITY_FIELDS",
    "LaunchBindingKey",
    "LaunchCapability",
    "LaunchStrategy",
    "Locality",
    "MachineCapabilities",
    "Model",
    "ModelProvider",
    "ModelProviderProbe",
    "OWNERSHIP_METADATA",
    "PROVIDER_PROBE_REGISTRY",
    "ProviderProbeRegistry",
    "build_execution_policy",
    "combine_capabilities",
    "coordinator_gate_from_event",
    "discover_execution_facts",
    "endpoint_locality",
    "expand_compatibility",
    "legacy_local_compatibility",
    "load_compatibility_bindings",
    "provider_locality",
    "prove_launch_invocation",
    "register_provider_probe",
    "resolve_mode_c_execution",
    "resolve_targets",
    "safe_endpoint_for_context",
    "serialize_execution_policy",
    "serialize_execution_target",
    "serialize_launch_candidate",
    "unregister_provider_probe",
]
